"""add mostrar_montos to usuarios

Revision ID: 2c7ffe3d367a
Revises: 94c983171544
Create Date: 2026-06-06 21:35:45.933916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7ffe3d367a'
down_revision: Union[str, Sequence[str], None] = '94c983171544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('mostrar_montos', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'mostrar_montos')
    # ### end Alembic commands ###
