"""Creacion inicial de todas las tablas del sistema

Revision ID: 5e4ef7869196
Revises: e00d41d220a9
Create Date: 2026-06-03 17:32:51.947768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4ef7869196'
down_revision: Union[str, Sequence[str], None] = 'e00d41d220a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
