"""add mostrar_montos to ejercicio

Revision ID: 94c983171544
Revises: 9a15d16c1ce9
Create Date: 2026-06-06 21:22:49.411417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c983171544'
down_revision: Union[str, Sequence[str], None] = '9a15d16c1ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ejercicios', sa.Column('mostrar_montos', sa.Boolean(), server_default='true', nullable=True, comment='Permite ocultar/mostrar montos en el sistema'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ejercicios', 'mostrar_montos')
    # ### end Alembic commands ###
