"""add_estado_flujo_to_programas

Revision ID: 9a15d16c1ce9
Revises: c6a9335fdf0b
Create Date: 2026-06-06 18:49:46.999388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a15d16c1ce9'
down_revision: Union[str, Sequence[str], None] = 'c6a9335fdf0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogo_programas', sa.Column('estado_flujo', sa.String(), server_default='configuracion', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogo_programas', 'estado_flujo')
    # ### end Alembic commands ###
