"""add_trazabilidad_avances

Revision ID: c43b685c3a64
Revises: e3cbaffbf420
Create Date: 2026-06-11 22:35:59.938514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43b685c3a64'
down_revision: Union[str, Sequence[str], None] = 'e3cbaffbf420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trazabilidad_avances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programacion_avance_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['programacion_avance_id'], ['programacion_avances.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trazabilidad_avances_id'), 'trazabilidad_avances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trazabilidad_avances_id'), table_name='trazabilidad_avances')
    op.drop_table('trazabilidad_avances')
    # ### end Alembic commands ###
