"""Creacion inicial de todas las tablas del sistema

Revision ID: e00d41d220a9
Revises: 
Create Date: 2026-06-03 16:47:11.181069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00d41d220a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_fuentes_financiamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(), nullable=False, comment='Ej. 5.02'),
    sa.Column('descripcion', sa.String(), nullable=False, comment='Ej. FAISMUN'),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_fuentes_financiamiento_id'), 'catalogo_fuentes_financiamiento', ['id'], unique=False)
    op.create_table('catalogo_pmd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_pmd_id'), 'catalogo_pmd', ['id'], unique=False)
    op.create_table('catalogo_unidades_administrativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('plazas', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_unidades_administrativas_id'), 'catalogo_unidades_administrativas', ['id'], unique=False)
    op.create_table('ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio_planeacion', sa.DateTime(), nullable=True, comment='Cuándo abre el sistema para armar el POA'),
    sa.Column('fecha_fin_planeacion', sa.DateTime(), nullable=True, comment='Cuándo cierra la creación de programas'),
    sa.Column('planeacion_abierta', sa.Boolean(), nullable=True, comment='Switch manual de emergencia'),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio')
    )
    op.create_index(op.f('ix_ejercicios_id'), 'ejercicios', ['id'], unique=False)
    op.create_table('captura_periodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio_reporte', sa.DateTime(), nullable=False, comment='Abre la subida de evidencia'),
    sa.Column('fecha_fin_reporte', sa.DateTime(), nullable=False, comment='Cierra la subida de evidencia'),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captura_periodos_id'), 'captura_periodos', ['id'], unique=False)
    op.create_table('catalogo_programas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('programa', sa.String(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('unidad_administrativa_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ),
    sa.ForeignKeyConstraint(['unidad_administrativa_id'], ['catalogo_unidades_administrativas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_programas_id'), 'catalogo_programas', ['id'], unique=False)
    op.create_table('techos_financieros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('unidad_administrativa_id', sa.Integer(), nullable=False),
    sa.Column('fuente_financiamiento_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ),
    sa.ForeignKeyConstraint(['fuente_financiamiento_id'], ['catalogo_fuentes_financiamiento.id'], ),
    sa.ForeignKeyConstraint(['unidad_administrativa_id'], ['catalogo_unidades_administrativas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techos_financieros_id'), 'techos_financieros', ['id'], unique=False)
    op.create_table('componentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['programa_id'], ['catalogo_programas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_componentes_id'), 'componentes', ['id'], unique=False)
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('meta', sa.Integer(), nullable=False, comment='Meta total anual'),
    sa.Column('componente_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['componente_id'], ['componentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_id'), 'actividades', ['id'], unique=False)
    op.create_table('inter_actividades_pmd',
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('pmd_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['pmd_id'], ['catalogo_pmd.id'], ),
    sa.PrimaryKeyConstraint('actividad_id', 'pmd_id')
    )
    op.create_table('programacion_metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad_programada', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False, comment='Número del mes (1-12)'),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programacion_metas_id'), 'programacion_metas', ['id'], unique=False)
    op.create_table('programacion_avances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avance_meta', sa.Integer(), nullable=True, comment='Cantidad real alcanzada'),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('BORRADOR', 'ENVIADO', 'CORRECCION', 'FINALIZADO', name='statusavance'), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comentarios_revision', sa.Text(), nullable=True, comment='Feedback del revisor si lo rechaza'),
    sa.Column('programacion_meta_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['programacion_meta_id'], ['programacion_metas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programacion_meta_id')
    )
    op.create_index(op.f('ix_programacion_avances_id'), 'programacion_avances', ['id'], unique=False)
    op.create_table('programacion_evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programacion_avance_id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(), nullable=False, comment='Ej. reporte_enero_final.pdf'),
    sa.Column('url_archivo', sa.String(), nullable=False, comment='Ruta en el servidor: /uploads/2026/01/reporte.pdf'),
    sa.Column('mime_type', sa.String(), nullable=False, comment='Ej. application/pdf, image/jpeg'),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['programacion_avance_id'], ['programacion_avances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programacion_evidencias_id'), 'programacion_evidencias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programacion_evidencias_id'), table_name='programacion_evidencias')
    op.drop_table('programacion_evidencias')
    op.drop_index(op.f('ix_programacion_avances_id'), table_name='programacion_avances')
    op.drop_table('programacion_avances')
    op.drop_index(op.f('ix_programacion_metas_id'), table_name='programacion_metas')
    op.drop_table('programacion_metas')
    op.drop_table('inter_actividades_pmd')
    op.drop_index(op.f('ix_actividades_id'), table_name='actividades')
    op.drop_table('actividades')
    op.drop_index(op.f('ix_componentes_id'), table_name='componentes')
    op.drop_table('componentes')
    op.drop_index(op.f('ix_techos_financieros_id'), table_name='techos_financieros')
    op.drop_table('techos_financieros')
    op.drop_index(op.f('ix_catalogo_programas_id'), table_name='catalogo_programas')
    op.drop_table('catalogo_programas')
    op.drop_index(op.f('ix_captura_periodos_id'), table_name='captura_periodos')
    op.drop_table('captura_periodos')
    op.drop_index(op.f('ix_ejercicios_id'), table_name='ejercicios')
    op.drop_table('ejercicios')
    op.drop_index(op.f('ix_catalogo_unidades_administrativas_id'), table_name='catalogo_unidades_administrativas')
    op.drop_table('catalogo_unidades_administrativas')
    op.drop_index(op.f('ix_catalogo_pmd_id'), table_name='catalogo_pmd')
    op.drop_table('catalogo_pmd')
    op.drop_index(op.f('ix_catalogo_fuentes_financiamiento_id'), table_name='catalogo_fuentes_financiamiento')
    op.drop_table('catalogo_fuentes_financiamiento')
    # ### end Alembic commands ###
