"""add_usuario_unidad_asociacion

Revision ID: e3cbaffbf420
Revises: 2c7ffe3d367a
Create Date: 2026-06-09 15:12:42.078323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3cbaffbf420'
down_revision: Union[str, Sequence[str], None] = '2c7ffe3d367a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_unidad_asociacion',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidad_administrativa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unidad_administrativa_id'], ['catalogo_unidades_administrativas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'unidad_administrativa_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_unidad_asociacion')
    # ### end Alembic commands ###
